name: first_Workflow
on:
  push:
    inputs:
      description:
        description: "Greeting Message"
        default: "Students"
        required: true
        type: string

jobs:
  greet:
    runs-on: windows-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{inputs.description}}"
      - name: Checkout repository code and allow tests to run
        uses: actions/checkout@v4
      - name: Build
        run: npm install
      - name: Run tests
