name: ZAP_Baseline_Scan
on: 
   push:
jobs:
   Security_Testing_Setup:
      runs-on: windows-latest
      steps:
        - name: ZAP Scan
          uses: zaproxy/action-baseline@v0.11.0
          with:
             target: 'https://juice-shop.herokuapp.com/#'
